### ISSUE TITLE
Doesn't compile on RaspberryPi

### ISSUE THREAD

**Issue by stawiski** [msalau/rl78flash#14]
There's a warning:
> pi@raspberrypi:~/rl78flash $ make
> cc -O2 -Wall -Wextra -Werror   -c -o src/rl78.o src/rl78.c
> cc -O2 -Wall -Wextra -Werror   -c -o src/main.o src/main.c
> src/main.c: In function 'main':
> src/main.c:106:35: error: comparison is always false due to limited range of data type [-Werror=type-limits]
>                  || MODE_MIN_VALUE > mode)
>                                    ^
> cc1: all warnings being treated as errors
> make: *** [<builtin>: src/main.o] Error 1

**Comment by msalau** [comment]
Hi @stawiski 

Thanks for reporting and providing a fix!

Regards,
Maksim
