### ISSUE TITLE
Entering programming mode

### ISSUE THREAD

**Issue by astrelsky** [msalau/rl78flash#20]
I have a blank R5F100PLAFB which I am struggling to get into programming mode. No matter what I do the rl78 does not respond. Is rl78flash supposed to automatically put the chip into programming mode? If not, how do you manage to do so? I have tried using a teensy 4.0 to for it into programming mode as specified in section 29.10 of the RL78/G13 user manual.

I am using this [USB to Serial Breakout](https://www.sparkfun.com/products/12731) to communicate with the chip. I also have the 1kΩ pull up resistors for TOOL0 and RESET as well as the 1n4148 diodes as shown in hw/rl78s-hw.png. I have tried with and without the 0.47uF capacitor between REGC/VSS as well as the 0.1uF capacitors between VDD/VSS and VEDD/VESS. I have attempted using rl78flash in all 4 modes each with/without the invert reset parameter.

**Comment by astrelsky** [comment]
:man_facepalming: turned out that I had the rl78 on my breakout board the wrong way.

**Comment by Hokoshi** [comment]
I often get stuck at the program voltage. That was 4.5V on the spec, right?

**Comment by astrelsky** [comment]
> I often get stuck at the program voltage. That was 4.5V on the spec, right?

I used 3.3V which is the default -p option.
