### ISSUE TITLE
rl78s-hw.sch file can not open normaly.

### ISSUE THREAD

**Issue by Yeo0o** [msalau/rl78flash#25]
I downloaded rl78s-hw.sch,but can not open normaly.
I had use Altium Designer (20.0.13) open it, it's nothing.
![image](https://github.com/msalau/rl78flash/assets/44898481/078ddda4-7f4e-426f-bed7-c4e78807eb0d) 

I had switch to Pads Logic(9.5),it said this:
<img width="423" alt="41fd7c1726aa42d5e4387a4e5152d35" src="https://github.com/msalau/rl78flash/assets/44898481/4a533f23-c54b-41a3-9172-9cca2b42900e">

Is there any problem with this sch file?

**Comment by msalau** [comment]
The file has been created using [gEDA](http://www.geda-project.org/) not Altium Designer.
