### ISSUE TITLE
Windows  FAILED baud rate set

### ISSUE THREAD

**Issue by Yeo0o** [msalau/rl78flash#26]
Hello, thanks for your code. But I have some problem with use.
I can flash R5F100MG with "Renesas Flash Programmer" by E1 hardware.
But I switch to “USB to DB9“ and “rl78flash” like:
```
rl78flash -b 500000 -vivavv com5 test-20220704.mot
rl78flash v0.7.0
                Open port: \\.\com5
Using communication mode 1
                Flush IO buffers
                Flush IO buffers
Send 1-byte data for setting mode
                send(1): 3A
                recv(1): 3A
Send "Set Baud Rate" command (baud=500000bps, voltage=3.3V)
                send(7): 01 03 9A 02 21 40 03
                recv(7): 01 03 9A 02 21 40 03
                recv(0):
FAILED baud rate set
Initialization failed
                Close port
```

By the way, I had install ch340 driver succeed and choose the right com number. Beacuse the DB9 port does not have VDD pin, so I had give the 5 volt by switching power supply to my device.

**Comment by msalau** [comment]
Hello @Yeo0o 

“USB to DB9“ usually means a USB to RS232 converter, but a "USB to UART" converter is required for flashing.
RS232 level (-12V..-5V and +5V..+12V) are not compatible with UART (0V and 5V) and may damage the MCU.
Please find a USB to UART converter.

I.e.:
Such adapters are not suitable for the task:
![image](https://github.com/msalau/rl78flash/assets/1215136/54b516d7-9d90-4a45-87c0-a1cd8759d5c1)

You need something like this:
![image](https://github.com/msalau/rl78flash/assets/1215136/e4a52760-5452-471b-99f6-535e1503dec9)

**Comment by Yeo0o** [comment]
Thanks for your reply. I had change my hardware to ‘USB to UART’ and try it again. But it does not received any byte.

By the way, I use breadboard and dupont wire to connected wire which is 'Mode 1'  in 'rl78s-hw.png', I don not have diode, so I changed to light emitting diode. All these wires are connecxted. Should I change ‘light emitting diode’ to another kind diode?
When I run cmd in terminal , the “send flag LED” in “USB to UART “module flickering, but the recevie flag doesn’ t flicker.

There are terminal printfed:
`
rl78flash -b 500000 -vivavv com6 test-20220704.mot
rl78flash v0.7.0
                Open port: \\.\com6
Using communication mode 1
                Flush IO buffers
                Flush IO buffers
Send 1-byte data for setting mode
                send(1): 3A
                recv(0):
Send "Set Baud Rate" command (baud=500000bps, voltage=3.3V)
                send(7): 01 03 9A 02 21 40 03
                recv(0):
                recv(0):
FAILED baud rate set
Initialization failed
                Close port

`

<img width="594" alt="2" src="https://github.com/msalau/rl78flash/assets/44898481/afbf329c-2bc5-40e7-bca9-aed8ed176758">

**Comment by msalau** [comment]
Hi @Yeo0o 

```
send(1): 3A
recv(0):
```
and
```
send(7): 01 03 9A 02 21 40 03
recv(0):
```
mean that the LED is not suitable for the job. `recv` should contain the very same byte sequence as `send`. The diode makes this feedback.

Please find a proper diode. A Schottky diode is the best candidate, since it has lower voltage drop comparaed to a regular diode.

**Comment by Yeo0o** [comment]
Thanks for your reply. Now i can buy Schottky diode, there are 'SR160,SR180,SR1100,SR240,SR260,SR2100,SR360,SR3100,SR540,SR560,SR5100,SR5150' ，what kind of parameter shloud I choose？

**Comment by msalau** [comment]
Hi @Yeo0o 
The lower forward voltage drop - the better.
SR240 should do the job.

**Comment by Yeo0o** [comment]
Thks again.I had chagned the LED to SR240 Schottky diode,it worded.
