### ISSUE TITLE
Windows Failed

### ISSUE THREAD

**Issue by codingkiller** [msalau/rl78flash#6]
I can flash the R5F100GC with the "Renesas Flash Programmer",but run rl78flash like:
    rl78flash.exe -viva COM21 abc.mot
it always return:
    failed
    Initialization failed

it happens here:
    rl78_send_cmd(fd, CMD_BAUD_RATE_SET, buf, 2);
    int len = 0;
    unsigned char data[3];
    int rc = rl78_recv(fd, &data, &len, 3);
    if (RESPONSE_OK != rc)
    {
        fprintf(stderr, "FAILED\n");
        return rc;
    }

what can i do to run it right?

**Comment by msalau** [comment]
Hi,

What hardware do You use to communicate with the microcontroller? Do you use 2-wire or 1-wire mode? Do you use RTS or DTR as RESET?

Please try mode 3: `rl78flash.exe -viva -m3 COM21 abc.mot`

It this doesn't help, please, add some debug output with extra -v options and post it here. 
E.g.: `rl78flash.exe -vivavv COM21 abc.mot`
Information about hardware used will be of great value too.

Hope this will help,
Maksim.

**Comment by codingkiller** [comment]
Hi,

1-wire mode,no use of RTS or DTR .

I tried mode 3,but it always return the same command that I've sended,here is the log:

rl78flash.exe -vivavv -m3 COM21 abc.mot
    Open port:\\.\COM21
Using communication mode 3
    Flush IO buffers
    Flush IO buffers
Send 1-byte data for setting mode
    send(1): 3A
    recv(1):  3A
Send "Set Baud Rate" command(baud=115200bps,voltage=3.3v)
    send(7):01 03 9A 00 20 43 03
    recv(7): 01 03 9A 00 20 43 03
    recv(0):
FAILED
Initialization failed
    Close port

**Comment by msalau** [comment]
Hi,

It is not possible to program internal flash without Reset. RFP needs it too.
To program an MCU 4 wires shall be connected: Vcc/EVcc, GND, RESET and TOOL0. This is true for all programming tools including RFP.

Please, provide schematic, if possible. What type of USB-UART converter do you use?

Maksim

**Comment by codingkiller** [comment]
Hi Maksim,
I finished my work with RFP, Thanks for your help.I'll close this issue now.
